### ISSUE TITLE
Cannot get module to work with ALF 5.0c community

### ISSUE THREAD

**Issue by deajan** [rouxemmanuel/DigitalSigning#1]
Hello,

I've installed the modules from http://alfresco-plugins.googlecode.com/svn/realeses/ into a fresh Alfresco 5.0c community setup, running on CentOS 7 x64.

I've created some test signatures with the following commands
```
$ openssl genrsa -out ./mykey.key 2048
$ openssl req -new -x509 -days 365 -key ./mykey.key -out ./mycert.crt
$ openssl pkcs12 -export -inkey mykey.key -in mycert.crt -out mycert.p12
```

Whenever i try to install the signature via the signature dashlet, i get a "please wait while..." (actually mine is French) ajax message that will stay forever.

Here's the corresponding log from my alfresco.log

```
22:01:16,653 DEBUG [org.alfresco.plugin.digitalSigning.webscript.SignUpload] [http-apr-8080-exec-7] Retrieve parameters
22:01:16,913 ERROR [freemarker.runtime] [http-apr-8080-exec-7] Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> signingKey.properties["dgtsgn:keyAlgorithm"]  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 443]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> ${signingKey.properties["dgtsgn:keyAl...  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 441]
    #if keyInfos??  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 424]
----------

Java stack trace (for programmers):
----------
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:382)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.IfBlock.accept(IfBlock.java:84)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:217)
        at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:955)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:470)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:454)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:532)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:600)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:380)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:261)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
22:01:16,925 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-7] Exception from executeScript - redirecting to status template error: 02140000 Wrapped Exception (with status template): 02140012 Erreur lors du traitement du mod?le 'The following has evaluated to null or missing:
==> signingKey.properties["dgtsgn:keyAlgorithm"]  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 443]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${signingKey.properties["dgtsgn:keyAl...  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 441]'. Veuillez contacter votre administrateur syst?me.
org.springframework.extensions.webscripts.WebScriptException: 02140000 Wrapped Exception (with status template): 02140012 Erreur lors du traitement du mod?le 'The following has evaluated to null or missing:
==> signingKey.properties["dgtsgn:keyAlgorithm"]  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 443]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${signingKey.properties["dgtsgn:keyAl...  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 441]'. Veuillez contacter votre administrateur syst?me.
        at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1126)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:470)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:454)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:532)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:600)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:380)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:261)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.alfresco.service.cmr.repository.TemplateException: 02140012 Erreur lors du traitement du mod?le 'The following has evaluated to null or missing:
==> signingKey.properties["dgtsgn:keyAlgorithm"]  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 443]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${signingKey.properties["dgtsgn:keyAl...  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 441]'. Veuillez contacter votre administrateur syst?me.
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:221)
        at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:955)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
        ... 33 more
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> signingKey.properties["dgtsgn:keyAlgorithm"]  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 443]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${signingKey.properties["dgtsgn:keyAl...  [in template "org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl" at line 2, column 441]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:382)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.IfBlock.accept(IfBlock.java:84)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:217)
        ... 36 more
```

Is there anything i did wrong with the signature creation or is it a form problem for ALF 5.0c ?
Tested on IE11 and Opera 28.

Regards,
Ozy.

**Comment by rouxemmanuel** [comment]
Hello,

I need your certificate and your certificate password to test it.

Regards,
Emmanuel

**Comment by deajan** [comment]
Hello,

Certificate is available here: 
http://www.netpower.fr/projects/ALF_testcert.p12
Password is: super

**Comment by deajan** [comment]
Update:
It must indeed have to do with my certificate, i have the same behavior in ALF 4.2c.
What do you use to generate your certs please ?
I guess my X509 p12 certs generated with openssl aren't okay with your plugin.

**Comment by deajan** [comment]
Finally found the solution. Hopefully this will help people who have had headaches like me.
The alias was missing in the p12 file.

The right commands to create a valid digital signature for this plugin are

```
openssl req -new -x509 -nodes -days 365 -newkey rsa:2048 -keyout testcert.key -out testcert.crt
openssl pkcs12 -export -inkey testcert.key -in testcert.crt -out testcert.p12 -name "Signature Orsiris de Jong"
```

**Comment by cantwait** [comment]
There should be a validation for this, I already added to my local copy. Thanks anyway, this thread was really helpful

**Comment by amet123** [comment]
I try this now show error
DerInputStream rejects tag type 45
