### ISSUE TITLE
 Failed to execute goal org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 missing  missing: org/codehaus/plexus/archiver/jar/JarArchiver

### ISSUE THREAD

**Issue by antoarva** [rouxemmanuel/DigitalSigning#16]
l have added manually the plugin 3.0.3 as you refer in issue #8  but l can't execute the mvn install command. What else I sould add?

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\User>cd C:\Users\User\Documents\GitHub\DigitalSigning\DigitalSigningAlf
resco

C:\Users\User\Documents\GitHub\DigitalSigning\DigitalSigningAlfresco>mvn install

[INFO] Scanning for projects...
[WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is mi
ssing, no dependency information available
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
org.alfresco.plugin:digitalSigningAlfresco:amp:1.1.0
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artif
actId} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alfresco Digital Signing Plugin 1.1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.sourcesense.maven:maven-nosnapshot-plugin:jar:0.0.7 is
 missing, no dependency information available
[WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is mi
ssing, no dependency information available
[INFO]
[INFO] --- maven-nosnapshot-plugin:0.0.7:strip (default) @ digitalSigningAlfresc
o ---
[WARNING] The POM for com.sourcesense.maven:maven-nosnapshot-plugin:jar:0.0.7 is
 missing, no dependency information available
[INFO] Storing noSnapshotVersion: 1.1.0
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ digitalSig
ningAlfresco ---
[WARNING] Using platform encoding (Cp1253 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\User\Documents\GitHub\Digita
lSigning\DigitalSigningAlfresco\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ digitalSignin
gAlfresco ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ di
gitalSigningAlfresco ---
[WARNING] Using platform encoding (Cp1253 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\User\Documents\GitHub\Digita
lSigning\DigitalSigningAlfresco\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ digit
alSigningAlfresco ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ digitalSigningAlfr
esco ---
[INFO]
[INFO] --- maven-amp-plugin:3.0.3:amp (default-amp) @ digitalSigningAlfresco ---

[WARNING] Error injecting: org.alfresco.maven.plugin.amp.AmpMojo
java.lang.NoClassDefFoundError: org/codehaus/plexus/archiver/jar/JarArchiver
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
        at java.lang.Class.getDeclaredConstructors(Class.java:1906)
        at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.
java:245)
        at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorB
indingImpl.java:99)
        at com.google.inject.internal.InjectorImpl.createUninitializedBinding(In
jectorImpl.java:658)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(Injec
torImpl.java:882)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecurs
ive(InjectorImpl.java:805)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(Injector
Impl.java:282)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImp
l.java:214)
        at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorIm
pl.java:1006)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java
:1038)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java
:1001)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java
:1051)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClas
s.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(Provider
InternalFactory.java:81)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.prov
ision(InternalFactoryToInitializableAdapter.java:53)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInt
ernalFactory.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.p
rovision(ProvisionListenerStackCallback.java:115)
        at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanSchedul
er.java:176)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.p
rovision(ProvisionListenerStackCallback.java:126)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(P
rovisionListenerStackCallback.java:68)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(Provid
erInternalFactory.java:63)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(
InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:10
16)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)

        at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)

        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:5
1)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContai
ner.java:263)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContai
ner.java:255)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfigu
redMojo(DefaultMavenPluginManager.java:517)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:121)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.archiver.jar.Ja
rArchiver
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadCl
ass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:239)
        ... 55 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.454 s
[INFO] Finished at: 2016-02-02T15:57:25+02:00
[INFO] Final Memory: 15M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:
amp (default-amp) on project digitalSigningAlfresco: Execution default-amp of go
al org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:amp failed: A required class
 was missing while executing org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:am
p: org/codehaus/plexus/archiver/jar/JarArchiver
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>org.alfresco.maven.plugin:maven-amp-plugin:3.0.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/User/.m2/repository/org/alfresco/maven/plugin/m
aven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.jar
[ERROR] urls[1] = file:/C:/Users/User/.m2/repository/org/codehaus/plexus/plexus-
utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.codehaus.plex
us.archiver.jar.JarArchiver
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContaine
rException

C:\Users\User\Documents\GitHub\DigitalSigning\DigitalSigningAlfresco>

**Comment by rouxemmanuel** [comment]
Hello,

It seems that your development environment (i think to your maven-amp-plugin-3.0.3.jar library) is corrupted. Try to redownload this library from Alfresco Maven repository.

Emmanuel.
