### ISSUE TITLE
No key file uploaded for user admin

### ISSUE THREAD

**Issue by moury** [rouxemmanuel/DigitalSigning#29]
I installed the amps files, but when i try to sign a document I receive the following error : No key file uploaded for user admin

**Comment by rouxemmanuel** [comment]
Hello,

Can you give me the full stack trace in alfresco.log ?

Thanks.
Regards,
Emmanuel

**Comment by LearnAlfresco** [comment]
I have the same error too. Can you please help resolve?

**Comment by LearnAlfresco** [comment]
ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-3] Exception from executeScript - redirecting to status template error: 04170005 Wrapped Exception (with status template): 04170109 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/doclist.get.js': 04170108 Failed to execute search:  +@cm\:modified:[2017\-5\-10T00\:00\:00.000 TO 2017\-5\-17T23\:59\:59.999] +@cm\:modifier:"admin" +TYPE:"cm:content" -TYPE:"cm:systemfolder" -TYPE:"fm:forums" -TYPE:"fm:forum" -TYPE:"fm:topic" -TYPE:"fm:post" +(TYPE:"content" OR TYPE:"app:filelink" OR TYPE:"folder")
org.springframework.extensions.webscripts.WebScriptException: 04170005 Wrapped Exception (with status template): 04170109 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/doclist.get.js': 04170108 Failed to execute search:  +@cm\:modified:[2017\-5\-10T00\:00\:00.000 TO 2017\-5\-17T23\:59\:59.999] +@cm\:modifier:"admin" +TYPE:"cm:content" -TYPE:"cm:systemfolder" -TYPE:"fm:forums" -TYPE:"fm:forum" -TYPE:"fm:topic" -TYPE:"fm:post" +(TYPE:"content" OR TYPE:"app:filelink" OR TYPE:"folder")
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)

Caused by: org.alfresco.scripts.ScriptException: 04170109 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/doclist.get.js': 04170108 Failed to execute search:  +@cm\:modified:[2017\-5\-10T00\:00\:00.000 TO 2017\-5\-17T23\:59\:59.999] +@cm\:modifier:"admin" +TYPE:"cm:content" -TYPE:"cm:systemfolder" -TYPE:"fm:forums" -TYPE:"fm:forum" -TYPE:"fm:topic" -TYPE:"fm:post" +(TYPE:"content" OR TYPE:"app:filelink" OR TYPE:"folder")

Caused by: org.alfresco.error.AlfrescoRuntimeException: 04170108 Failed to execute search:  +@cm\:modified:[2017\-5\-10T00\:00\:00.000 TO 2017\-5\-17T23\:59\:59.999] +@cm\:modifier:"admin" +TYPE:"cm:content" -TYPE:"cm:systemfolder" -TYPE:"fm:forums" -TYPE:"fm:forum" -TYPE:"fm:topic" -TYPE:"fm:post" +(TYPE:"content" OR TYPE:"app:filelink" OR TYPE:"folder")
Caused by: org.alfresco.repo.search.impl.lucene.LuceneQueryParserException: 04170107 Request failed 500 /solr4/alfresco/alfresco?wt=json&fl=DBID%2Cscore&rows=50&df=TEXT&start=0&locale=en_US&alternativeDic=DEFAULT_DICTIONARY&sort=%40cm%3Amodified+desc&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON


2017-05-17 13:51:30,834 ERROR [org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl] [defaultAsyncAction7] Failed to execute asynchronous action: Action[ id=560c68d0-624c-4bc2-8fed-73701c798218, node=null ]: 04170114 JMagick transformation failed to write output file
org.alfresco.error.AlfrescoRuntimeException: 04170122 Creation of thumbnail 'doclib' failed
	at org.alfresco.repo.thumbnail.CreateThumbnailActionExecuter.executeImpl(CreateThumbnailActionExecuter.java:206)
	at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:267)
	at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:839)
	at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:740)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1$1.execute(AsynchronousActionExecutionQueueImpl.java:423)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:326)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1.doWork(AsynchronousActionExecutionQueueImpl.java:432)
	at org.alfresco.repo.tenant.TenantUtil.runAsWork(TenantUtil.java:119)
	at org.alfresco.repo.tenant.TenantUtil.runAsTenant(TenantUtil.java:88)
	at org.alfresco.repo.tenant.TenantUtil$1.doWork(TenantUtil.java:62)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at org.alfresco.repo.tenant.TenantUtil.runAsUserTenant(TenantUtil.java:58)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper.run(AsynchronousActionExecutionQueueImpl.java:435)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.alfresco.service.cmr.repository.ContentIOException: 04170115 Content conversion failed: 
   reader: ContentAccessor[ contentUrl=store://2017/5/17/13/51/564bdb14-5fc6-4f2b-832d-c084dad01fda.bin, mimetype=application/pdf, size=198864, encoding=UTF-8, locale=en_US]
   writer: ContentAccessor[ contentUrl=store://C:\ALFRES~1\tomcat\temp\Alfresco\FailoverTransformer_intermediate_ProxyContentTransformer_6900000290554446268.png, mimetype=image/png, size=0, encoding=UTF-8, locale=en_US]

**Comment by rouxemmanuel** [comment]
Hi,

Can you test with the new 1.2.0 release and come back to me if the problem still exists ?

Regards,
Emmanuel

**Comment by LearnAlfresco** [comment]
I will try that out.

Thanks and appreciate your help.
Lakshmi.

**Comment by LearnAlfresco** [comment]
Emmanuel,
I tried getting the amp files directly but I cannot see them here. It shows the release that was done 2 years ago. Can you please help?

https://github.com/rouxemmanuel/images/tree/9cb4bcb81b51d519ea3b711f4801ea1b441440ff/realeses

Thanks,
Lakshmi.

**Comment by rouxemmanuel** [comment]
Hello,

I've updated release files :

- Alfresco AMP : https://github.com/rouxemmanuel/images/blob/master/realeses/digitalSigningAlfresco.amp?raw=true

- Share AMP : https://github.com/rouxemmanuel/images/blob/master/realeses/digitalSigningShare.amp?raw=true

Regards,
Emmanuel

**Comment by LearnAlfresco** [comment]
Thank you. Appreciate your help!

Lakshmi.

**Comment by macartuche** [comment]
where i can upload the digital sign?
