### ISSUE TITLE
Unable to create amp package for "DigitalSigningShare"

### ISSUE THREAD

**Issue by SrinivasDhulipalla** [rouxemmanuel/DigitalSigning#31]
I was trying to add Digital signature in alfresco community edition 5.1.
Downloaded and created 2 amps packages but for "DigitalSigningShare" its show the following error 

#mvn -X install
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /usr/local/apache-maven-3.3.9
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/local/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/local/apache-maven-3.3.9/conf/settings.xml
[DEBUG] Reading user settings from /home/vasu/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/local/apache-maven-3.3.9/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/vasu/.m2/toolchains.xml
[DEBUG] Using local repository at /home/vasu/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/vasu/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Verifying availability of /home/vasu/.m2/repository/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.pom from [central (https://repo.maven.apache.org/maven2, default, releases)]
[WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is missing, no dependency information available
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=1, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=3, ConflictResolver.conflictItemCount=1, DefaultDependencyCollector.collectTime=39, DefaultDependencyCollector.transformTime=8}
[DEBUG] org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3:
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.1:runtime
[DEBUG] Verifying availability of /home/vasu/.m2/repository/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.jar from [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Looking up lifecyle mappings for packaging amp from ClassRealm[plexus.core, parent: null]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead. @ 
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead. @ 
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[ERROR] Unresolveable build extension: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: amp @ line 5, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead. @ 
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead. @ 
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[ERROR] Unresolveable build extension: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: amp @ line 5, column 15

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.alfresco.plugin:digitalSigningShare:1.1.0 (/home/vasu/Music/DigitalSigning-master/DigitalSigningShare/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
org.apache.maven.plugin.PluginManagerException: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:846)
	at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:196)
	at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:99)
	at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
	at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1295)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:441)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:620)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:411)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts(DefaultMavenPluginManager.java:908)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:839)
	... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
	... 29 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 32 more
[ERROR]     Unknown packaging: amp @ line 5, column 15
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

---------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
I ve copied the files in "/home/user/.m2/repository/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.jar" -Still problem exist

Could you please give some inputs to resolve this is issue

**Comment by rouxemmanuel** [comment]
Hello,

Let me test it and go back to you.

Regards,
Emmanuel

**Comment by Funies** [comment]
Hi,

I am facing the same issue.

Was this ever resolved?

**Comment by rouxemmanuel** [comment]
Hi,

Try to run your maven command with the -U option.

Regards,
Emmanuel

**Comment by Funies** [comment]
Hi,

I ran it with this command and I'm getting the same error. See below.
It look like it is looking for the maven-amp-plugin-3.0.3.jar from this repository: https://repo.maven.apache.org/maven2. 
I tried to download it manual from this repository: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/ and it still gave me the same error message.

ubuntu@ubuntu-Mecer:~/Tutorial_home/DigitalSigning-master/DigitalSigningShare$ 
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.pom
[WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.jar
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Could not find artifact org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in central (https://repo.maven.apache.org/maven2) @ 
[ERROR] Unknown packaging: amp @ line 5, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.alfresco.plugin:digitalSigningShare:1.2.0 (/home/ubuntu/Tutorial_home/DigitalSigning-master/DigitalSigningShare/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.alfresco.maven.plugin:maven-amp-plugin:3.0.3 or one of its dependencies could not be resolved: Could not find artifact org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 in central (https://repo.maven.apache.org/maven2) -> [Help 2]
[ERROR]     Unknown packaging: amp @ line 5, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by Funies** [comment]
Hi Emmanuel,

I am still experiencing the issue. Are you able to assist?

**Comment by Funies** [comment]
Hi,

Resolved the issue. The pom file is missing pluginRepositories. copied the ones from the repo pom and it worked.

**Comment by rouxemmanuel** [comment]
Ok.
Thank you for the feed back.
I closed this issue.

Regards,
Emmanuel
