### ISSUE TITLE
Error signing document

### ISSUE THREAD

**Issue by pqhcker** [rouxemmanuel/DigitalSigning#48]
Hi Emmanuel

I have the following error.
Can you help me? The cerfiticate was uploaded to alfresco sucess
![captura](https://user-images.githubusercontent.com/5551726/34229906-9e417ce8-e59b-11e7-99f5-973e75b53708.PNG)

**Comment by rouxemmanuel** [comment]
Hi

Can you check the alfresco.log file to see if there is an error ?

Emmanuel

**Comment by pqhcker** [comment]
Yeah... I found that

2017-12-21 09:34:09,395 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-5] Exception from executeScript: 11210004 Wrapped Exception (with status template): 11210024 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js': 11210023 com.itextpdf.text.pdf.PdfSignatureAppearance.setCertificate(Ljava/security/cert/Certificate;)V
org.springframework.extensions.webscripts.WebScriptException: 11210004 Wrapped Exception (with status template): 11210024 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js': 11210023 com.itextpdf.text.pdf.PdfSignatureAppearance.setCertificate(Ljava/security/cert/Certificate;)V
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.alfresco.scripts.ScriptException: 11210024 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js': 11210023 com.itextpdf.text.pdf.PdfSignatureAppearance.setCertificate(Ljava/security/cert/Certificate;)V
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:211)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 37 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 11210023 com.itextpdf.text.pdf.PdfSignatureAppearance.setCertificate(Ljava/security/cert/Certificate;)V
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:533)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	... 42 more
Caused by: java.lang.NoSuchMethodError: com.itextpdf.text.pdf.PdfSignatureAppearance.setCertificate(Ljava/security/cert/Certificate;)V
	at com.itextpdf.text.pdf.security.MakeSignature.signDetached(MakeSignature.java:169)
	at com.itextpdf.text.pdf.security.MakeSignature.signDetached(MakeSignature.java:107)
	at org.alfresco.plugin.digitalSigning.service.SigningService.signPDFFile(SigningService.java:309)
	at org.alfresco.plugin.digitalSigning.service.SigningService.sign(SigningService.java:592)
	at org.alfresco.plugin.digitalSigning.script.SigningServiceScript.sign(SigningServiceScript.java:364)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_10._c_script_0(classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js:63)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_10.call(classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_10.call(classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_10.exec(classpath*:alfresco/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	... 43 more

**Comment by rouxemmanuel** [comment]
I think you have two itext jar files in your tomcat/webapps/alfresco/WEB-INF/lib folder.
You only need the itextpdf-5.5.11.jar in this folder.

Can you check, rename (with other extension) or delete the old version of jar and test again ?

Emmanuel

**Comment by pqhcker** [comment]
I got a new error, more specific... 

2017-12-21 17:31:31,675 ERROR [org.alfresco.plugin.digitalSigning.service.SigningService] [http-apr-8080-exec-6] [Minuta-Acta.pdf] java.io.IOException: Not enough space
2017-12-21 17:32:08,107 ERROR [org.alfresco.plugin.digitalSigning.service.SigningService] [http-apr-8080-exec-2] [Minuta-Acta.pdf] java.io.IOException: **Not enough space**

**Comment by pqhcker** [comment]
Hi.. Can you help me please?

**Comment by rouxemmanuel** [comment]
It seems that you have no more space left on the device where Alfresco is installed.

Can you check ?

Regards,
Emmanuel

**Comment by Katitanuma** [comment]
Thanks Emmanuel. 
It worked!
