### ISSUE TITLE
Exception when signing Document: Can't convert PDF to PDF/A, java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by junidb** [rouxemmanuel/DigitalSigning#67]
Hi, I got the following error when signing the document:  Can't convert PDF to PDF/A.  Error during conversion to PDF/A. 
The Alfresco version is Community - 6.2.0, am using version 1.2.1-20200415.015234 from #65. Pls help, thanks.

Below is the log:
` 2020-04-14 18:43:37,995  ERROR [digitalSigning.service.SigningService] [ajp-nio-127.0.0.1-8009-exec-16] Can't convert PDF to PDF/A.  Error during conversion to PDF/A.
java.io.IOException: Stream closed
        at java.base/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:165)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.InputStream.readNBytes(InputStream.java:396)
        at java.desktop/java.awt.color.ICC_Profile.getProfileDataFromStream(ICC_Profile.java:1040)
        at java.desktop/java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:1027)
        at org.apache.pdfbox.pdmodel.graphics.color.PDOutputIntent.configureOutputProfile(PDOutputIntent.java:112)
        at org.apache.pdfbox.pdmodel.graphics.color.PDOutputIntent.<init>(PDOutputIntent.java:49)
        at org.alfresco.plugin.digitalSigning.service.SigningService.convertPdfToPdfA(SigningService.java:1260)
        at org.alfresco.plugin.digitalSigning.service.SigningService.signPDFFile(SigningService.java:232)
        at org.alfresco.plugin.digitalSigning.service.SigningService.sign(SigningService.java:795)
        at org.alfresco.plugin.digitalSigning.script.SigningServiceScript.sign(SigningServiceScript.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_19._c_script_0(classpath*:alfresco/extension/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js:63)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_19.call(classpath*:alfresco/extension/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_19.call(classpath*:alfresco/extension/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_org_alfresco_plugin_digitalSigning_webscript_sign_sign_post_js_19.exec(classpath*:alfresco/extension/templates/webscripts/org/alfresco/plugin/digitalSigning/webscript/sign/sign.post.js)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
        at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
        at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
        at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:527)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:595)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:664)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:435)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:315)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:508)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-14 18:43:37,998  ERROR [digitalSigning.service.SigningService] [ajp-nio-127.0.0.1-8009-exec-16] [Memo - Persetujuan & Permohonan Pengadaan Perpanjangan Kontrak Maintenance HSM (Host Security Module).pdf] java.io.IOException: Can't convert PDF to PDF/A.  Error during conversion to PDF/A.
`

**Comment by rouxemmanuel** [comment]
Hi,

It seems that the problem is about your original PDF file. The program doesn't succeed in convert it into PDF/A format.

Can you test :
- With an other PDF file
- By disabling the PDF/A conversion when signing

Regards,
Emmanuel
