### ISSUE TITLE
Signature Not Verified

### ISSUE THREAD

**Issue by popoyorc** [rouxemmanuel/DigitalSigning#7]
Hi Sir Emmanuel,

I have successfully installed Digital Signing in Alfresco 4.2 c Community Edition. I can also sign documents without any errors. The only problem I encountered is with uploading certificate, but found the fix by using the openssl command that you provided in issue#1, using my p12 as input which is provided by my local CA. My question is how do I verify my signature which is issued by my local CA? Thanks.

**Comment by ananthu143** [comment]
I have successfully installed Digital Signing in Alfresco 5.0.d. bu i am not able to update the signature and certificates from dashlet.  nothing is happening while am creating Signature.

Alfresco Version 5.0.d

this is what am getting with out a key file.
Error during document signing : 07010080 No key file uploaded for user admin.

**Comment by popoyorc** [comment]
Look in issue #2 and #3 theyve resolved their problems.

**Comment by ananthu143** [comment]
how do I verify my signature?

**Comment by ananthu143** [comment]
Digital Signature as a work flow is possible?

**Comment by rouxemmanuel** [comment]
Hello,

I've written a java class to get informations from your certificate.
The project is named "DigitalSigningVerifySign".
You can :
- checkout this project
- run the command : mvn clean compile package
- and finally run the command : java -jar DigitalSigningVerifySign-1.0.0.jar "[Your certificate path (including the certificate file)]" [your certificate password]

This program will display the certificate informations in the console output.

Regards,
Emmanuel

**Comment by ananthu143** [comment]
yea got it, but this is we are doing outside of Alfresco, right? can we do the same thing in the pdf reader?

each user we need to run " java -jar DigitalSigningVerifySign-1.0.0.jar "[Your certificate path (including the certificate file)]" [your certificate password]" command?

**Comment by rouxemmanuel** [comment]
This class is just a tool to use when you didn't succed in updated tour certificats.

**Comment by rouxemmanuel** [comment]
You can sign a document (or many documents) in Workflow with javacript sign API

**Comment by ananthu143** [comment]
Hi Sir,
Am just new in Alfresco. can you please refer me how to use that API using JavaScript if you don't mind.

**Comment by rouxemmanuel** [comment]
If you want to sign a document in a Workflow step, use the following js code in your step :
	var parameters = new Object();
	parameters.keyPassword=keyPassword;
	parameters.document=document;
	parameters.destination=destination;
	parameters.reason=reason;
	parameters.location=location;
	parameters.contact=contact;
	parameters.position=position;
	parameters.field=field;
	parameters.page=page;
	parameters.locationX=locationX;
	parameters.locationY=locationY;
	parameters.marginX=marginX;
	parameters.marginY=marginY;
	parameters.height=height;
	parameters.width=width;
	parameters.depth=depth;
        parameters.pageNumber=pageNumber;
	
	digitalSigning.sign(parameters);

Regards,
Emmanuel

**Comment by popoyorc** [comment]
Why is it showing Signature Not Verified in a PDF file after signing?

**Comment by rouxemmanuel** [comment]
Because you certainly use a certificate self signed (generate by a command line). So the certificate wasn't generated by an authority and acrobat reader can't verify the signature against the authorities.

**Comment by popoyorc** [comment]
I'm pretty sure It doesn't have anything to do with my document viewer (Acrobat Reader). Yes, I am using a self signed certificate but I have added the CA to the trusted key store. I'm guessing It has something to do with java's cacerts, but as I have mentioned. I have also added my local CA (The one that signed my certificate) to java's keystore. or I think I have.

**Comment by popoyorc** [comment]
I used keytool to import my local CA to java using this. 

keytool -import -trustcacerts -keystore /path/to/cacerts -noprompt -alias myLocalCA -file myLocalCA.crt

**Comment by ananthu143** [comment]
Hi Sir,
i stuck on creating work flow. exactly where i need to place the code.?

**Comment by popoyorc** [comment]
I suggest you read about activiti a workflow engine. Maybe start from there?

**Comment by rouxemmanuel** [comment]
To have a verified signature, you need to import the crt file in "Trusted identities" of Adobe Reader 
- Edit --> Protection --> Manage Trsuted Identities
- Click on "Add contact"
- Select your crt file
- Select the contact added
- Click on "Trust" button
- In the new windows, select "Use this certificate as trusted root"
- Valid the windows and click on "Import" button

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
@ananthu143 yes I suggest you to read first activity documentation.

**Comment by popoyorc** [comment]
Thanks. I got it to work on a Windows environment. The problem is, when I open a PDF, it opens using a default viewer, in my case (Document Viewer) on a linux. What I did is add it to linuxs keystore. Not on Java. One more question tho @rouxemmanuel. I used a transparent signature.png image. Turns black when I sign documents. Any suggestions?? Thanks!

**Comment by rouxemmanuel** [comment]
I've nerver tested with a transparent png image.
Can you send me your png example ?

**Comment by popoyorc** [comment]
![ericsign](https://cloud.githubusercontent.com/assets/7122711/9036060/641c2a1a-3a10-11e5-9641-aabe660ff6ce.png)

**Comment by popoyorc** [comment]
Here I've attached the image i'm using.. It seems the transparency isn't applied when it is attached to a PDF...

**Comment by rouxemmanuel** [comment]
I've modifed the code to keep transparency.
I've sucessfully tested.
Can you also test and go back to me ?

**Comment by popoyorc** [comment]
I currently don't have access to my machine right now but i'll get back to you as soon as I can. Thanks @rouxemmanuel

**Comment by popoyorc** [comment]
Hi @rouxemmanuel is this link updated? https://github.com/rouxemmanuel/images/blob/master/realeses/digitalSigningAlfresco.amp?raw=true

**Comment by rouxemmanuel** [comment]
Let me change the pom.xml to change to the community level.

**Comment by rouxemmanuel** [comment]
@popoyorc I've modified the two pom.xml and update the AMPs files to directly download them.

**Comment by rouxemmanuel** [comment]
@popoyorc is it OK for you (transparency) ?

**Comment by popoyorc** [comment]
Yes it's working fine now. Thank you very much @rouxemmanuel !

**Comment by rouxemmanuel** [comment]
You're welcome and thank you to help me improving this plugin.

**Comment by popoyorc** [comment]
I forgot to mention that I recieved and Error while building the plugin.. so I just used the AMP files.. Here is the build log

    [INFO] Scanning for projects...
    [WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is missing, no dependency information available
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Alfresco Digital Signing Plugin 1.1.0
    [INFO] ------------------------------------------------------------------------
    [WARNING] The POM for com.sourcesense.maven:maven-nosnapshot-plugin:jar:0.0.7 is missing, no dependency information available
    [WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is missing, no dependency information available
    [INFO] 
    [INFO] --- maven-nosnapshot-plugin:0.0.7:strip (default) @ digitalSigningAlfresco ---
    [WARNING] The POM for com.sourcesense.maven:maven-nosnapshot-plugin:jar:0.0.7 is missing, no dependency information available
    [INFO] Storing noSnapshotVersion: 1.1.0 
    [INFO] 
    [INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ digitalSigningAlfresco ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] skip non existing resourceDirectory /home/eric/Downloads/DigitalSigning-master/DigitalSigningAlfresco/src/main/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ digitalSigningAlfresco ---
    [INFO] Nothing to compile - all classes are up to date
    [INFO] 
    [INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ digitalSigningAlfresco ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] skip non existing resourceDirectory /home/eric/Downloads/DigitalSigning-master/DigitalSigningAlfresco/src/test/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ digitalSigningAlfresco ---
    [INFO] No sources to compile
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ digitalSigningAlfresco ---
    [INFO] No tests to run.
    [INFO] 
    [INFO] --- maven-amp-plugin:3.0.3:amp (default-amp) @ digitalSigningAlfresco ---
    [WARNING] The POM for org.alfresco.maven.plugin:maven-amp-plugin:jar:3.0.3 is missing, no dependency information available
    [WARNING] Error injecting: org.alfresco.maven.plugin.amp.AmpMojo
    java.lang.NoClassDefFoundError: org/codehaus/plexus/archiver/jar/JarArchiver
    	at java.lang.Class.getDeclaredConstructors0(Native Method)
    	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
    	at java.lang.Class.getDeclaredConstructors(Class.java:1855)
    	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
    	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
    	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:653)
    	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:863)
    	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:790)
    	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:278)
    	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:210)
    	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:986)
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1019)
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:982)
    	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1032)
    	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
    	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
    	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
    	at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
    	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
    	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
    	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
    	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
    	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
    	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
    	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
    	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
    	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
    	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
    	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
    	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
    	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
    	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:601)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.archiver.jar.JarArchiver
    	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
    	... 54 more
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.129s
    [INFO] Finished at: Thu Aug 06 17:34:54 PHT 2015
    [INFO] Final Memory: 14M/212M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:amp (default-amp) on project digitalSigningAlfresco: Execution default-amp of goal org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:amp failed: A required class was missing while executing org.alfresco.maven.plugin:maven-amp-plugin:3.0.3:amp: org/codehaus/plexus/archiver/jar/JarArchiver
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    plugin>org.alfresco.maven.plugin:maven-amp-plugin:3.0.3
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/home/eric/.m2/repository/org/alfresco/maven/plugin/maven-amp-plugin/3.0.3/maven-amp-plugin-3.0.3.jar
    [ERROR] urls[1] = file:/home/eric/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[project>org.alfresco.plugin:digitalSigningAlfresco:1.1.0, parent: ClassRealm[maven.api, parent: null]]]
    [ERROR] 
    [ERROR] -----------------------------------------------------: org.codehaus.plexus.archiver.jar.JarArchiver
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by rouxemmanuel** [comment]
@popoyorc see the issue #8 for this problem of dependency.

**Comment by FathiBenNasr** [comment]
Hello,
I am looking to include digital signature in my alfresco. I successfully installed your addon (thanks for the excellent wiki page) but don't know how to upload a digital certificate; i have a free one from comodo.
Could you please tell me how to upload a p12/pfx signature as when I try to sign a document, i get an error as follow: Erreur lors de la signature du document : 10241073 No key file uploaded for user xyz.
My alfresco server details:
Édition: Community
Numéro de version: 5.2.0 (r135134-b14)
Etiquette de version: Version et numéro de build Alfresco Content Services.
Schéma: 10 005 Numéro de schéma de base de données Alfresco Content Services.
